In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv(r"C:\Users\loneo\OneDrive\Documents\ev-charging-demand-segmentation\data\raw\EVChargingStationUsage.csv")

C:\Users\loneo\AppData\Local\Temp\ipykernel_27184\3935048766.py:1: DtypeWarning: Columns (0: User ID, 1: County, 2: Model Number) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r"C:\Users\loneo\OneDrive\Documents\ev-charging-demand-segmentation\data\raw\EVChargingStationUsage.csv")

In [3]:
data.head(3)

,Station Name,MAC Address,Org Name,Start Date,Start Time Zone,End Date,End Time Zone,Transaction Date (Pacific Time),Total Duration (hh:mm:ss),Charging Time (hh:mm:ss),...,Longitude,Currency,Fee,Ended By,Plug In Event Id,Driver Postal Code,User ID,County,System S/N,Model Number
0,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/29/2011 20:17,PDT,7/29/2011 23:20,PDT,7/29/2011 23:20,3:03:32,1:54:03,...,-122.160309,USD,0.0,Plug Out at Vehicle,3,95124.0,3284.0,NaN,NaN,NaN
1,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 0:00,PDT,7/30/2011 0:02,PDT,7/30/2011 0:02,0:02:06,0:01:54,...,-122.160309,USD,0.0,Customer,4,94301.0,4169.0,NaN,NaN,NaN
2,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 8:16,PDT,7/30/2011 12:34,PDT,7/30/2011 12:34,4:17:32,4:17:28,...,-122.160309,USD,0.0,Plug Out at Vehicle,5,94301.0,4169.0,NaN,NaN,NaN

In [4]:
print(data.shape)
print('\n')
print(data.columns)
print('\n')
print(data.dtypes)
print('\n')
print(data.isnull().sum())
print('\n')
print(data.duplicated().sum())
print('\n')
print(data['Station Name'].value_counts())
print('\n')
print(data.info())
print('\n')
print(data.describe())
print('\n')

(259415, 33)


Index(['Station Name', 'MAC Address', 'Org Name', 'Start Date',
       'Start Time Zone', 'End Date', 'End Time Zone',
       'Transaction Date (Pacific Time)', 'Total Duration (hh:mm:ss)',
       'Charging Time (hh:mm:ss)', 'Energy (kWh)', 'GHG Savings (kg)',
       'Gasoline Savings (gallons)', 'Port Type', 'Port Number', 'Plug Type',
       'EVSE ID', 'Address 1', 'City', 'State/Province', 'Postal Code',
       'Country', 'Latitude', 'Longitude', 'Currency', 'Fee', 'Ended By',
       'Plug In Event Id', 'Driver Postal Code', 'User ID', 'County',
       'System S/N', 'Model Number'],
      dtype='str')


Station Name                           str
MAC Address                            str
Org Name                               str
Start Date                             str
Start Time Zone                        str
End Date                               str
End Time Zone                          str
Transaction Date (Pacific Time)        str
Total Duration (hh:mm:ss)              str
Charging Time (hh:mm:ss)               str
Energy (kWh)                       float64
GHG Savings (kg)                   float64
Gasoline Savings (gallons)         float64
Port Type                              str
Port Number                          int64
Plug Type                              str
EVSE ID                            float64
Address 1                              str
City                                   str
State/Province                         str
Postal Code                          int64
Country                                str
Latitude                           float64
Longitude                          float64
Currency                               str
Fee                                float64
Ended By                               str
Plug In Event Id                     int64
Driver Postal Code                 float64
User ID                             object
County                                 str
System S/N                         float64
Model Number                           str
dtype: object


Station Name                           0
MAC Address                            0
Org Name                               0
Start Date                             0
Start Time Zone                        0
End Date                               0
End Time Zone                          0
Transaction Date (Pacific Time)      209
Total Duration (hh:mm:ss)              0
Charging Time (hh:mm:ss)               0
Energy (kWh)                           0
GHG Savings (kg)                       0
Gasoline Savings (gallons)             0
Port Type                              9
Port Number                            0
Plug Type                              0
EVSE ID                            78948
Address 1                              0
City                                   0
State/Province                         0
Postal Code                            0
Country                                0
Latitude                               0
Longitude                              0
Currency                            1788
Fee                                    0
Ended By                             248
Plug In Event Id                       0
Driver Postal Code                  8402
User ID                             7677
County                             84665
System S/N                         78948
Model Number                       78948
dtype: int64


4


Station Name
PALO ALTO CA / HAMILTON #2        23721
PALO ALTO CA / HAMILTON #1        14888
PALO ALTO CA / WEBSTER #1         14432
PALO ALTO CA / BRYANT #2          14389
PALO ALTO CA / HIGH #4            13898
PALO ALTO CA / BRYANT #1          13436
PALO ALTO CA / WEBSTER #2         12669
PALO ALTO CA / CAMBRIDGE #1       11163
PALO ALTO CA / HIGH #1            10756
PALO ALTO CA / WEBSTER #3         10484
PALO ALTO CA / TED THOMPSON #1     9814
PALO ALTO CA / CAMBRIDGE #2        9256
PALO ALTO CA / MPL #6              8996
PALO ALTO CA / HIGH #3             8317
PALO ALTO CA / MPL #4              7787
PALO ALTO CA / MPL #5              7544
PALO ALTO CA / HIGH #2             6930
PALO ALTO CA / RINCONADA LIB 3     6499
PALO ALTO CA / RINCONADA LIB 1     6212
PALO ALTO CA / BRYANT #6           5857
PALO ALTO CA / RINCONADA LIB 2     5553
PALO ALTO CA / BRYANT #5           5332
PALO ALTO CA / CAMBRIDGE #5        4556
PALO ALTO CA / CAMBRIDGE #3        4476
PALO ALTO CA / BRYANT #3           4475
PALO ALTO CA / BRYANT #4           3598
PALO ALTO CA / CAMBRIDGE #4        3428
PALO ALTO CA / TED THOMPSON #3     2455
PALO ALTO CA / TED THOMPSON #4     2226
PALO ALTO CA / TED THOMPSON #2     2217
PALO ALTO CA / MPL #2              1535
PALO ALTO CA / MPL #3              1420
PALO ALTO CA / MPL #1              1044
PALO ALTO CA / BRYANT # 1            13
PALO ALTO CA / SHERMAN 3              8
PALO ALTO CA / SHERMAN 1              7
PALO ALTO CA / SHERMAN 7              4
PALO ALTO CA / SHERMAN 4              4
PALO ALTO CA / SHERMAN 2              4
PALO ALTO CA / SHERMAN 6              3
PALO ALTO CA / SHERMAN 8              2
PALO ALTO CA / SHERMAN 14             2
PALO ALTO CA / SHERMAN 9              1
PALO ALTO CA / SHERMAN 5              1
PALO ALTO CA / SHERMAN 15             1
PALO ALTO CA / SHERMAN 11             1
PALO ALTO CA / SHERMAN 17             1
Name: count, dtype: int64


<class 'pandas.DataFrame'>
RangeIndex: 259415 entries, 0 to 259414
Data columns (total 33 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Station Name                     259415 non-null  str
 1   MAC Address                      259415 non-null  str
 2   Org Name                         259415 non-null  str
 3   Start Date                       259415 non-null  str
 4   Start Time Zone                  259415 non-null  str
 5   End Date                         259415 non-null  str
 6   End Time Zone                    259415 non-null  str
 7   Transaction Date (Pacific Time)  259206 non-null  str
 8   Total Duration (hh:mm:ss)        259415 non-null  str
 9   Charging Time (hh:mm:ss)         259415 non-null  str
 10  Energy (kWh)                     259415 non-null  float64
 11  GHG Savings (kg)                 259415 non-null  float64
 12  Gasoline Savings (gallons)       259415 non-null  float64
 13  Port Type                        259406 non-null  str
 14  Port Number                      259415 non-null  int64
 15  Plug Type                        259415 non-null  str
 16  EVSE ID                          180467 non-null  float64
 17  Address 1                        259415 non-null  str
 18  City                             259415 non-null  str
 19  State/Province                   259415 non-null  str
 20  Postal Code                      259415 non-null  int64
 21  Country                          259415 non-null  str
 22  Latitude                         259415 non-null  float64
 23  Longitude                        259415 non-null  float64
 24  Currency                         257627 non-null  str
 25  Fee                              259415 non-null  float64
 26  Ended By                         259167 non-null  str
 27  Plug In Event Id                 259415 non-null  int64
 28  Driver Postal Code               251013 non-null  float64
 29  User ID                          251738 non-null  object
 30  County                           174750 non-null  str
 31  System S/N                       180467 non-null  float64
 32  Model Number                     180467 non-null  str
dtypes: float64(9), int64(3), object(1), str(20)
memory usage: 121.0+ MB
None


        Energy (kWh)  GHG Savings (kg)  Gasoline Savings (gallons)  \
count  259415.000000     259415.000000               259415.000000
mean        8.544277          3.588596                    1.072306
std         7.185462          3.017894                    0.901776
min         0.010000          0.004000                    0.001000
25%         3.784000          1.589000                    0.475000
50%         6.868634          2.885000                    0.862000
75%        11.458340          4.813000                    1.438000
max        97.360000         40.891000                   12.219000

         Port Number       EVSE ID    Postal Code       Latitude  \
count  259415.000000  1.804670e+05  259415.000000  259415.000000
mean        1.591627  1.462973e+05   94302.315768      37.439565
std         0.491534  2.429677e+05       1.941657       0.009621
min         1.000000  3.792000e+03   94301.000000      37.422104
25%         1.000000  4.358300e+04   94301.000000      37.428318
50%         2.000000  1.074270e+05   94301.000000      37.444489
75%         2.000000  1.745590e+05   94303.000000      37.446613
max         2.000000  5.535441e+06   94306.000000      37.449375

           Longitude            Fee  Plug In Event Id  Driver Postal Code  \
count  259415.000000  259415.000000      2.594150e+05       251013.000000
mean     -122.151264       1.097481      1.188685e+08        94170.308255
std         0.015382       1.934408      4.057750e+08         4249.837126
min      -122.163239       0.000000      1.000000e+00         1013.000000
25%      -122.162170       0.000000      1.573000e+03        94087.000000
50%      -122.158272       0.000000      3.573000e+03        94304.000000
75%      -122.145699       1.640000      6.340000e+03        94804.000000
max      -122.112480      84.560000      1.609436e+09        99354.000000

         System S/N
count  1.804670e+05
mean   1.443790e+11
std    2.483280e+10
min    1.023100e+11
25%    1.231100e+11
50%    1.427410e+11
75%    1.705410e+11
max    2.002410e+11

In [5]:
data['Station Name'].nunique()

47

In [6]:
print(data[['Start Date','End Date']].dtypes)

data['Start Date']=pd.to_datetime(data['Start Date'])
#data['End Date']=pd.to_datetime(data['End Date'])

Start Date    str
End Date      str
dtype: object

In [7]:
data['Start Date'].min()

Timestamp('2011-07-29 20:17:00')

In [8]:
data['Start Date'].max()

Timestamp('2020-12-31 18:19:00')

In [9]:
data['Start Date'].sort_values()[0:5]

0   2011-07-29 20:17:00
1   2011-07-30 00:00:00
2   2011-07-30 08:16:00
3   2011-07-30 14:51:00
4   2011-07-30 18:51:00
Name: Start Date, dtype: datetime64[us]

In [10]:
data[data['Station Name']=='PALO ALTO CA / HAMILTON #2']

,Station Name,MAC Address,Org Name,Start Date,Start Time Zone,End Date,End Time Zone,Transaction Date (Pacific Time),Total Duration (hh:mm:ss),Charging Time (hh:mm:ss),...,Longitude,Currency,Fee,Ended By,Plug In Event Id,Driver Postal Code,User ID,County,System S/N,Model Number
10,PALO ALTO CA / HAMILTON #2,000D:6F00:009E:D39E,City of Palo Alto,2011-08-02 12:26:00,PDT,8/2/2011 13:27,PDT,8/2/2011 13:27,1:00:50,1:00:43,...,-122.160263,USD,0.00,Plug Out at Vehicle,8,NaN,0.0,NaN,NaN,NaN
12,PALO ALTO CA / HAMILTON #2,000D:6F00:009E:D39E,City of Palo Alto,2011-08-02 19:03:00,PDT,8/2/2011 21:30,PDT,8/2/2011 21:30,2:26:46,2:26:43,...,-122.160263,USD,0.00,Customer,9,94301.0,4169.0,NaN,NaN,NaN
14,PALO ALTO CA / HAMILTON #2,000D:6F00:009E:D39E,City of Palo Alto,2011-08-03 08:18:00,PDT,8/3/2011 10:02,PDT,8/3/2011 10:02,1:44:32,1:40:14,...,-122.160263,USD,0.00,Plug Out at Vehicle,11,94301.0,2670.0,NaN,NaN,NaN
17,PALO ALTO CA / HAMILTON #2,000D:6F00:009E:D39E,City of Palo Alto,2011-08-03 22:33:00,PDT,8/4/2011 8:32,PDT,8/4/2011 8:32,9:59:07,3:09:13,...,-122.160263,USD,0.00,Plug Out at Vehicle,12,94301.0,2670.0,NaN,NaN,NaN
19,PALO ALTO CA / HAMILTON #2,000D:6F00:009E:D39E,City of Palo Alto,2011-08-04 17:45:00,PDT,8/4/2011 18:19,PDT,8/4/2011 18:19,0:34:29,0:34:23,...,-122.160263,NaN,0.00,Plug Out at Vehicle,13,94043.0,2828.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257290,PALO ALTO CA / HAMILTON #2,0024:B100:0002:965D,City of Palo Alto,2020-11-03 05:00:00,PST,11/3/2020 7:02,PST,11/3/2020 7:04,2:02:42,1:47:46,...,-122.160324,USD,1.14,Plug Out at Vehicle,9415,95008.0,3184101,Santa Clara County,1.739410e+11,CT4020-HD-GW
257294,PALO ALTO CA / HAMILTON #2,0024:B100:0002:965D,City of Palo Alto,2020-11-03 07:42:00,PST,11/3/2020 16:17,PST,11/3/2020 16:18,8:34:51,8:34:34,...,-122.160324,USD,10.98,Plug Out at Vehicle,9416,95112.0,4762101,Santa Clara County,1.739410e+11,CT4020-HD-GW
257330,PALO ALTO CA / HAMILTON #2,0024:B100:0002:965D,City of Palo Alto,2020-11-03 16:45:00,PST,11/3/2020 21:43,PST,11/3/2020 21:44,4:58:02,4:57:51,...,-122.160324,USD,3.54,Plug Out at Vehicle,9417,94568.0,1554761,Santa Clara County,1.739410e+11,CT4020-HD-GW
257332,PALO ALTO CA / HAMILTON #2,0024:B100:0002:965D,City of Palo Alto,2020-11-03 17:29:00,PST,11/3/2020 19:07,PST,11/3/2020 19:08,1:38:20,1:38:02,...,-122.160324,USD,1.28,Plug Out at Vehicle,9418,94306.0,853500,Santa Clara County,1.739410e+11,CT4020-HD-GW
257337,PALO ALTO CA / HAMILTON #2,0024:B100:0002:965D,City of Palo Alto,2020-11-04 04:54:00,PST,11/4/2020 6:50,PST,11/4/2020 6:52,1:56:47,1:53:10,...,-122.160324,USD,1.20,Plug Out at Vehicle,9419,95008.0,3184101,Santa Clara County,1.739410e+11,CT4020-HD-GW